In [1]:
# Import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
loans_df = pd.read_csv("./resources/loan_status.csv")
loans_df.head(10)

,Loan_Status,Current_Loan_Amount,Term,Credit_Score,Annual_Income,Years_in_current_job,Home_Ownership,Purpose,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,Bankruptcies,Tax_Liens
0,Fully_Paid,99999999,Short_Term,741.0,2231892.0,8_years,Own_Home,Debt_Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
1,Fully_Paid,217646,Short_Term,730.0,1184194.0,<_1_year,Home_Mortgage,Debt_Consolidation,10855.08,19.6,10.0,13,1,122170,272052.0,1.0,0.0
2,Fully_Paid,548746,Short_Term,678.0,2559110.0,2_years,Rent,Debt_Consolidation,18660.28,22.6,33.0,4,0,437171,555038.0,0.0,0.0
3,Fully_Paid,99999999,Short_Term,728.0,714628.0,3_years,Rent,Debt_Consolidation,11851.06,16.0,76.0,16,0,203965,289784.0,0.0,0.0
4,Fully_Paid,99999999,Short_Term,740.0,776188.0,<_1_year,Own_Home,Debt_Consolidation,11578.22,8.5,25.0,6,0,134083,220220.0,0.0,0.0
5,Fully_Paid,234124,Short_Term,727.0,693234.0,10+_years,Rent,Debt_Consolidation,14211.24,24.7,46.0,10,1,28291,107052.0,1.0,0.0
6,Fully_Paid,666204,Long_Term,723.0,1821967.0,10+_years,Home_Mortgage,Debt_Consolidation,17612.24,22.0,34.0,15,0,813694,2004618.0,0.0,0.0
7,Not_Paid,317108,Long_Term,687.0,1133274.0,8_years,Rent,Debt_Consolidation,9632.81,17.4,53.0,4,0,60287,126940.0,0.0,0.0
8,Fully_Paid,465410,Long_Term,688.0,1722654.0,3_years,Rent,Buy_House,15647.45,22.3,30.0,7,0,107559,488356.0,0.0,0.0
9,Fully_Paid,99999999,Short_Term,746.0,1749748.0,10+_years,Home_Mortgage,Debt_Consolidation,19247.19,20.0,32.0,17,0,224390,295240.0,0.0,0.0

In [2]:
# Generate our categorcial variable list
loans_cat = loans_df.dtypes[loans_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
loans_df[loans_cat].nunique()

Loan_Status              2
Term                     2
Years_in_current_job    11
Home_Ownership           4
Purpose                  7
dtype: int64

In [3]:
# Check the unique value counts to see if binning is required
loans_df.Years_in_current_job.value_counts()

10+_years    13149
2_years       3225
3_years       2997
<_1_year      2699
5_years       2487
4_years       2286
1_year        2247
6_years       2109
7_years       2082
8_years       1675
9_years       1467
Name: Years_in_current_job, dtype: int64

In [4]:
# checking to see if ["column"] works
loans_df["Years_in_current_job"].value_counts()

10+_years    13149
2_years       3225
3_years       2997
<_1_year      2699
5_years       2487
4_years       2286
1_year        2247
6_years       2109
7_years       2082
8_years       1675
9_years       1467
Name: Years_in_current_job, dtype: int64

In [9]:
# Create a OneHotEncoder instancce
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(loans_df[loans_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names_out(loans_cat)
encode_df.head()

,Loan_Status_Fully_Paid,Loan_Status_Not_Paid,Term_Long_Term,Term_Short_Term,Years_in_current_job_10+_years,Years_in_current_job_1_year,Years_in_current_job_2_years,Years_in_current_job_3_years,Years_in_current_job_4_years,Years_in_current_job_5_years,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [10]:
# merge one-hot encoded features and drop the originals
loans_df = loans_df.merge(encode_df,left_index=True,right_index=True)
loans_df = loans_df.drop(loans_cat,1)
loans_df.head()

/Users/armandolatigo/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Current_Loan_Amount,Credit_Score,Annual_Income,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,99999999,741.0,2231892.0,29200.53,14.9,29.0,18,1,297996,750090.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,217646,730.0,1184194.0,10855.08,19.6,10.0,13,1,122170,272052.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,548746,678.0,2559110.0,18660.28,22.6,33.0,4,0,437171,555038.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,99999999,728.0,714628.0,11851.06,16.0,76.0,16,0,203965,289784.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,99999999,740.0,776188.0,11578.22,8.5,25.0,6,0,134083,220220.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [11]:
# Remove loan status target from features data
y = loans_df.Loan_Status_Fully_Paid
X = loans_df.drop(columns=["Loan_Status_Fully_Paid","Loan_Status_Not_Paid"])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
# Create random forest classifier
rf_model=RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model=rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred=rf_model.predict(X_test_scaled)
print(f"Random Forest Predictive Accuracy:{accuracy_score(y_test,y_pred):.3f}")

Random Forest Predictive Accuracy:0.849

In [14]:
# Define the model - Deep Neural Network
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 24
hidden_nodes_layer2 = 12

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#Complie the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

2022-03-06 15:23:06.968776: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
854/854 [==============================] - 1s 711us/step - loss: 0.4224 - accuracy: 0.8374
Epoch 2/50
854/854 [==============================] - 1s 722us/step - loss: 0.3867 - accuracy: 0.8491
Epoch 3/50
854/854 [==============================] - 1s 741us/step - loss: 0.3825 - accuracy: 0.8492
Epoch 4/50
854/854 [==============================] - 1s 701us/step - loss: 0.3802 - accuracy: 0.8493
Epoch 5/50
854/854 [==============================] - 1s 705us/step - loss: 0.3788 - accuracy: 0.8494
Epoch 6/50
854/854 [==============================] - 1s 690us/step - loss: 0.3778 - accuracy: 0.8492
Epoch 7/50
854/854 [==============================] - 1s 698us/step - loss: 0.3766 - accuracy: 0.8495
Epoch 8/50
854/854 [==============================] - 1s 735us/step - loss: 0.3761 - accuracy: 0.8494
Epoch 9/50
854/854 [==============================] - 1s 702us/step - loss: 0.3753 - accuracy: 0.8497
Epoch 10/50
854/854 [==============================] - 1s 717us/step - loss: 0.3746 - accuracy: 0.8494
Epoch 11/50
854/854 [==============================] - 1s 698us/step - loss: 0.3741 - accuracy: 0.8493
Epoch 12/50
854/854 [==============================] - 1s 705us/step - loss: 0.3737 - accuracy: 0.8495
Epoch 13/50
854/854 [==============================] - 1s 726us/step - loss: 0.3728 - accuracy: 0.8496
Epoch 14/50
854/854 [==============================] - 1s 697us/step - loss: 0.3722 - accuracy: 0.8495
Epoch 15/50
854/854 [==============================] - 1s 714us/step - loss: 0.3715 - accuracy: 0.8497
Epoch 16/50
854/854 [==============================] - 1s 708us/step - loss: 0.3712 - accuracy: 0.8500
Epoch 17/50
854/854 [==============================] - 1s 702us/step - loss: 0.3707 - accuracy: 0.8496
Epoch 18/50
854/854 [==============================] - 1s 732us/step - loss: 0.3705 - accuracy: 0.8502
Epoch 19/50
854/854 [==============================] - 1s 704us/step - loss: 0.3696 - accuracy: 0.8497
Epoch 20/50
854/854 [==============================] - 1s 745us/step - loss: 0.3695 - accuracy: 0.8502
Epoch 21/50
854/854 [==============================] - 1s 726us/step - loss: 0.3692 - accuracy: 0.8500
Epoch 22/50
854/854 [==============================] - 1s 693us/step - loss: 0.3687 - accuracy: 0.8502
Epoch 23/50
854/854 [==============================] - 1s 702us/step - loss: 0.3680 - accuracy: 0.8505
Epoch 24/50
854/854 [==============================] - 1s 691us/step - loss: 0.3679 - accuracy: 0.8505
Epoch 25/50
854/854 [==============================] - 1s 732us/step - loss: 0.3679 - accuracy: 0.8505
Epoch 26/50
854/854 [==============================] - 1s 714us/step - loss: 0.3672 - accuracy: 0.8503
Epoch 27/50
854/854 [==============================] - 1s 698us/step - loss: 0.3673 - accuracy: 0.8509
Epoch 28/50
854/854 [==============================] - 1s 712us/step - loss: 0.3667 - accuracy: 0.8504
Epoch 29/50
854/854 [==============================] - 1s 693us/step - loss: 0.3666 - accuracy: 0.8511
Epoch 30/50
854/854 [==============================] - 1s 701us/step - loss: 0.3663 - accuracy: 0.8509
Epoch 31/50
854/854 [==============================] - 1s 738us/step - loss: 0.3658 - accuracy: 0.8512
Epoch 32/50
854/854 [==============================] - 1s 706us/step - loss: 0.3653 - accuracy: 0.8514
Epoch 33/50
854/854 [==============================] - 1s 710us/step - loss: 0.3651 - accuracy: 0.8514
Epoch 34/50
854/854 [==============================] - 1s 690us/step - loss: 0.3652 - accuracy: 0.8509
Epoch 35/50
854/854 [==============================] - 1s 734us/step - loss: 0.3649 - accuracy: 0.8518
Epoch 36/50
854/854 [==============================] - 1s 716us/step - loss: 0.3649 - accuracy: 0.8510
Epoch 37/50
854/854 [==============================] - 1s 705us/step - loss: 0.3645 - accuracy: 0.8508
Epoch 38/50
854/854 [==============================] - 1s 732us/step - loss: 0.3643 - accuracy: 0.8520
Epoch 39/50
854/854 [==============================] - 1s 716us/step - loss: 0.3640 - accuracy: 0.8516
Epoch 40/50
854/854 [==============================] - 1s 693us/step - loss: 0.3639 - accuracy: 0.8519
Epoch 41/50
854/854 [==============================] - 1s 720us/step - loss: 0.3634 - accuracy: 0.8516
Epoch 42/50
854/854 [==============================] - 1s 696us/step - loss: 0.3628 - accuracy: 0.8516
Epoch 43/50
854/854 [==============================] - 1s 742us/step - loss: 0.3634 - accuracy: 0.8524
Epoch 44/50
854/854 [==============================] - 1s 707us/step - loss: 0.3627 - accuracy: 0.8515
Epoch 45/50
854/854 [==============================] - 1s 722us/step - loss: 0.3624 - accuracy: 0.8527
Epoch 46/50
854/854 [==============================] - 1s 721us/step - loss: 0.3624 - accuracy: 0.8514
Epoch 47/50
854/854 [==============================] - 1s 712us/step - loss: 0.3620 - accuracy: 0.8529
Epoch 48/50
854/854 [==============================] - 1s 746us/step - loss: 0.3620 - accuracy: 0.8521
Epoch 49/50
854/854 [==============================] - 1s 758us/step - loss: 0.3619 - accuracy: 0.8525
Epoch 50/50
854/854 [==============================] - 1s 730us/step - loss: 0.3615 - accuracy: 0.8521

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

285/285 - 0s - loss: 0.3934 - accuracy: 0.8463 - 222ms/epoch - 780us/step
Loss: 0.3934166729450226, Accuracy: 0.8462552428245544